language: python

python:
  - "3.5"

sudo: required

dist: trusty

services:
  - mysql

install:
  - "pip install -r requirements/ci.txt"

before_script:
  - cd src/config/settings/
  - ln -s ci.py default.py
  - cd ../../../
  - mysql -uroot -e 'create database xaasadmin;'

script:
  - flake8 --exclude=migrations,requirements --max-line-length=120 ./src
  - coverage run src/manage.py test --exclude-tag=no_travis

notifications:
  email:
    recipients:
      - gregory.charmier@gmail.com
    on_success: always
    on_failure: always
