apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testuserclusterole
rules:
- apiGroups: [""]
  resources:
  - pods/log
  - persistentvolumeclaims
  - namespaces
  - events
  - pods
  - secrets
  - serviceaccounts
  - configmaps
  - services
  - pods/portforward
  - pods/exec
  - endpoints
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - persistentvolumes
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - clusterrolebindings
  - rolebindings
  - roles
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - restricted
  verbs:
  - use
