apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows group ideverp to access basic resources
kind: ClusterRoleBinding
metadata:
  # nom du clusterRoleBindings entre le cluster role et le group AD
  name: {{name}} 
subjects:
- kind: Group
  # nom du group AD
  name: oidc:{{groupName}} 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  # nom du cluster Role précédemment déployé
  name: {{clusterRoleName}} 
  apiGroup: rbac.authorization.k8s.io